### ISSUE TITLE
Several errors/failure in SINDy-MPC MATLAB package

### ISSUE THREAD

**Issue by kv3100123** [eurika-kaiser/SINDY-MPC#1]
Hi Kaiser,
I am self-learning DataDriven Control on Youtube channels and found this Code. After I downloaded the code. I have encountered several issues inside the Code itself.
The simplest one is DATA_ENSEMBLE and ENSEMBLE_DATA inconsistency.
Then I found the 'using fmincon nonlinear constraints problems' in MPC_F8 which has not been solved by myself yet.
In the EX_F8_SI_DelayDMDc, I think the 
`%% Prediction over traning phase`
Here `Hu'` should be modified to something like `Hu(1,1:end-1)'` right ?
`[xDMDc,~] = lsim(sysmodel_DMDc,Hu(1,1:end-1)',tspan(1:end-1),x(1,:)'-xmean');`

I cannot run EX_F8_SI_NARX on ode45

Thank you

**Comment by eurika-kaiser** [comment]
The error has been fixed. Please run EX_F8_SI_NARX_Ensemble.m if you want to train the F8 system on ensemble data.
