### ISSUE TITLE
MPC F8 Error using sqpinterface

### ISSUE THREAD

**Issue by purepuremilk-zz** [eurika-kaiser/SINDY-MPC#4]
1. for F8 case, when running MPC_F8__ModelComparison.m or MPC_F8.m, it returned errors: 

"Error using sqpInterface Nonlinear constraint function is undefined at initial point. Fmincon cannot continue."

This is relatively easy to solve, essentially, values of LBdu and UBdu are not assigned, which results in NaN in CONSFUN and further the fmincon. By adding LBdu = -0.3; UBdu = 0.5; in the for iM = 1:Nmodels loop, the DelayDMDc and SINDYc should run just fine. 

2. However, for the NARX model, the same error pops up after about 20mins run: 

"Error using sqpInterface
Objective function is undefined at initial point. Fmincon cannot continue."

I don't really know the causes of this problem, but I suspect the cost function diverges with the trained neural network. It might because of different network initialization, but I have tried both the EX_F8_SI_NARX_Ensemble.m and the EX_F8_SI_NARX.m twice each. No good luck so far. I suggest authors also upload their trained models to ensure consistency with the paper results. 

Updates: 

The second error is solved! A simple reason, you have to use the new upload: EX-F8_SI_NARX_Ensemble.m to generate your neural network model. However, my previous trials fail because the **data path in this new upload is different**!! All you need to do if change the path to DATA/F8, along with other .mat files. 

After that, you probably need to change a few lines in the MPC_F8_ModelComparison because of the dimension changes by the ensemble NARX model. Then you should be good to go!

**Comment by AuchAaron** [comment]
> 1. for F8 case, when running MPC_F8__ModelComparison.m or MPC_F8.m, it returned errors:
> 
> "Error using sqpInterface Nonlinear constraint function is undefined at initial point. Fmincon cannot continue."
> 
> This is relatively easy to solve, essentially, values of LBdu and UBdu are not assigned, which results in NaN in CONSFUN and further the fmincon. By adding LBdu = -0.3; UBdu = 0.5; in the for iM = 1:Nmodels loop, the DelayDMDc and SINDYc should run just fine.
> 
> 2. However, for the NARX model, the same error pops up after about 20mins run:
> 
> "Error using sqpInterface Objective function is undefined at initial point. Fmincon cannot continue."
> 
> I don't really know the causes of this problem, but I suspect the cost function diverges with the trained neural network. It might because of different network initialization, but I have tried both the EX_F8_SI_NARX_Ensemble.m and the EX_F8_SI_NARX.m twice each. No good luck so far. I suggest authors also upload their trained models to ensure consistency with the paper results.
> 
> Updates:
> 
> The second error is solved! A simple reason, you have to use the new upload: EX-F8_SI_NARX_Ensemble.m to generate your neural network model. However, my previous trials fail because the **data path in this new upload is different**!! All you need to do if change the path to DATA/F8, along with other .mat files.
> 
> After that, you probably need to change a few lines in the MPC_F8_ModelComparison because of the dimension changes by the ensemble NARX model. Then you should be good to go!

hi！When I running  MPC_F8__ModelComparison.m, by adding LBdu = -0.3; UBdu = 0.5; in the  iM = 1, the DelayDMDc  is in bug：
‘The initial condition X0 must be a numeric vector without any NaN or Inf’
how can I deal with it?
